### ISSUE TITLE
Move requirements inside setup.py gated by version

### ISSUE THREAD

**Issue by cooperlees** [zalando/python-nsenter#12]
argparse is not really needed except in older version of Python. How do you feel about moving them into `setup.py` and gating them for < 2.7 and < 3.3 ?

Context: @ Facebook we build modules into our own wheels and auto generate dependencies. Your modules, even with Python 3.6 today insists on these modules so our automation co-operates.

Many thanks for the module!

**Comment by hjacobs** [comment]
Sounds good, feel free to open a PR!
