### ISSUE TITLE
import referring to installed module rather than its code

### ISSUE THREAD

**Issue by hacker-h** [zalando/python-nsenter#17]
nsenter/__main__.py imports the installed module rather than its code which enforces a reinstallation of the module after each code change

**Comment by hjacobs** [comment]
Can you describe the problem in a different way? Sorry, I don't yet understand.

**Comment by hacker-h** [comment]
Nevermind, the import seems to be fine, however you e.g. can't run the __main__.py without having the module installed.

**Comment by hjacobs** [comment]
You can run it from the root/repo dir with:

```
python3 -m nsenter
```
