### ISSUE TITLE
Allow using nsenter for new processes (i.e. not knowing the PID)

### ISSUE THREAD

**Issue by hjacobs** [zalando/python-nsenter#5]
This is a very valid use case and should be supported by the nsenter library: http://stackoverflow.com/questions/30127569/start-multiprocessing-process-in-namespace

**Comment by cnelson** [comment]
So what's the ask here?  You want to be able to specify a path to an arbitrary path and use the open fd to that path to enter a namespace?  Something like:

    with Namespace(path='/var/run/netns/foo'):
        # output network interfaces as seen from within the mypid's net NS:
        subprocess.check_output(['ip', 'a'])

Would that solve the problem?

**Comment by hjacobs** [comment]
@cnelson I just found the StackOverflow question (http://stackoverflow.com/questions/30127569/start-multiprocessing-process-in-namespace) and I think that nobody should need to copy&paste the StackOverflow code for this specific use case --- it should be possible with the "nsenter" module.

So: yes, being able to pass in the path would be one possibility (obviously keeping everything backwards compatible).

I haven't thought much about it yet...

**Comment by cnelson** [comment]
Tossed up a quick PR as it was simpler than I thought it would be -- thoughts?
