### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando/python-nsenter#7]
Do you have plans to build this out any further?

**Comment by hjacobs** [comment]
@LappleApple this project is working as-is and I see no need to extend it.

**Comment by LappleApple** [comment]
@hjacobs  I would like to enhance the README to promote this project. Is the info [here](https://tech.zalando.com/blog/entering-kernel-namespaces-with-python/) still current? It includes useful details that make this project more interesting.

**Comment by hjacobs** [comment]
@LappleApple yes, the information in the blog post is mostly correct (we have Ubuntu 16.04 LTS now).

**Comment by LappleApple** [comment]
@hjacobs hey, this project is called both python-nsenter and nsenter. Can we call it python-nsenter to preempt any confusion with nsenter?

**Comment by hjacobs** [comment]
@LappleApple I think we should keep it as is: "python-nsenter" is the repository name (as git repos can contain any kind of language), but "nsenter" is the package name on PyPI (it makes no sense to prefix "python-" as PyPI is Python only :smirk: ).

**Comment by hjacobs** [comment]
The README could be changed of course...

**Comment by LappleApple** [comment]
Eh, it's good as-is. Will close this issue now. :)
